name: Pipeline CI/CD MLops

on:
  pull_request: 
    branches: [ dev ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: SetUp Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install requirements
        run: |
          # 1. Actualizar pip por estabilidad
          python -m pip install --upgrade pip

          # 2. Instalar manualmente las librerías principales en su versión de CPU/Linux
          pip install torch==2.11.0 --index-url https://download.pytorch.org/whl/cpu
          
          # 3. Instalar el resto de dependencias comunes para ciencia de datos y pruebas
          # Evitamos usar el requirements.txt problemático instalando lo necesario para el test
          pip install pandas numpy scikit-learn pytest mlflow

      - name: Run tests
        run: pytest ./python/credit_scoring/tests/test_model_creation.py
